# Generated by Django 4.2.8 on 2024-04-08 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_courseenroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='current_student',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='end_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.DateField(auto_now=True),
        ),
    ]
