# Generated by Django 4.2.8 on 2024-04-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_capacity_course_current_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(),
        ),
    ]
