# Generated by Django 4.2.8 on 2024-06-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_course_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='batch_time',
            field=models.TimeField(default='15:00:00'),
        ),
        migrations.AddField(
            model_name='course',
            name='days',
            field=models.JSONField(default=list),
        ),
    ]
