# Generated by Django 4.2.8 on 2024-06-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_course_batch_time_course_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='batch_time',
            field=models.TimeField(default='15:00:00Z'),
        ),
    ]
