# Generated by Django 4.2.8 on 2024-04-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_rename_courses_student_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contact_number',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_contact_number',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
