# Generated by Django 4.2.8 on 2024-01-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='is_instructor',
            field=models.BooleanField(default=False),
        ),
    ]
