# Generated by Django 4.2.8 on 2024-04-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usermodel_is_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='is_instructor',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='department',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='experience',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
