# Generated by Django 4.2.8 on 2024-04-08 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_usermodel_is_instructor_usermodel_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='department',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='last_name',
        ),
    ]
