# Generated by Django 4.2.8 on 2024-04-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_instructorprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorprofile',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
