# Generated by Django 4.2.8 on 2024-04-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_instructorprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorprofile',
            name='experience',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='subject',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
