# Generated by Django 4.2.8 on 2024-04-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_instructorprofile_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorprofile',
            name='experience',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
